#
print("안녕하세요! 다음 질문에 답하고 이야기를 완성하세요.")

sto1 = input("동물을 입력하세요 : ")
sto2 = input("이름을 입력하세요 : ")
sto3 = input("형용사를 입력하세요(00(이)고): ")
sto4 = input("색을 입력하세요(00색): ")
sto5 = input("형용사를 입력하세요: ")
sto6 = input("명사를 입력하세요: ")
sto7 = input("명사를 입력하세요: ")
sto8 = input("명사를 입력하세요: ")
sto9 = input("형용사를 입력하세요(00은): ")
sto10 = input("색을 입력하세요: ")
sto11 = input("명사를 입력하세요: ")
print("다음은 여러분이 만든 이야기입니다.")

print("저의 반려동물은",sto1 ,"이며 이름은",sto2 ,"입니다.")
print(sto3 ,"(이)고",sto4 ,"이며",sto5 ,"니다.")
print(sto2 ,"은(는)",sto6 ,",",sto7 ,",",sto8 ,"을(를) 먹습니다.")
print("가장 좋아하는 장난감은",sto9 ,sto10 ,sto11 ,"입니다.")
